=begin pod

=TITLE class X::Proc::Async::AlreadyStarted

=SUBTITLE Exception for when you call C<start> on an already started Proc::Async object

    class X::Proc::Async::AlreadyStarted is Exception { ... }

When you call C<start> twice on the same L<Proc::Async|/type/Proc::Async>
object, the second invocation will die with an
C<X::Proc::Async::AlreadyStarted> exception.

    my $proc = Proc::Async.new("echo");
    $proc.start;
    $proc.start;    # Process has already been started

=end pod
